# Generated by Django 3.2 on 2022-03-15 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='uploads/avatar-default-icon.png', upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='followed_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followed', to='post.profile'),
        ),
        migrations.AlterField(
            model_name='follow',
            name='follower_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='follower', to='post.profile'),
        ),
    ]
